name: Run tests

on:
  push:

jobs:
  run-tests-ce:
    strategy:
      matrix:
        tarantool-version: ["1.10", "2.5", "2.6", "2.7", "2.8", "2.10"]
      fail-fast: false
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3

      - uses: tarantool/setup-tarantool@v2
        with:
          tarantool-version: '${{ matrix.tarantool-version }}'

      - name: Install deps
        run: ./deps.sh

      - name: Run linter
        run: .rocks/bin/luacheck .

      - name: Run tests
        run: .rocks/bin/luatest -v
